"""Cascade on FKs

Revision ID: 17920b9f701f
Revises: 6bc8deda5332
Create Date: 2022-09-07 23:38:13.319309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17920b9f701f"
down_revision = "6bc8deda5332"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("comments_post_id_fkey", "comments", type_="foreignkey")
    op.drop_constraint("comments_author_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        None, "comments", "users", ["author_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "comments", "posts", ["post_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("posts_owner_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(
        None, "posts", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key("posts_owner_id_fkey", "posts", "users", ["owner_id"], ["id"])
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_author_id_fkey", "comments", "users", ["author_id"], ["id"]
    )
    op.create_foreign_key(
        "comments_post_id_fkey", "comments", "posts", ["post_id"], ["id"]
    )
    # ### end Alembic commands ###
