"""Posts model created and relationship to users

Revision ID: 462f2799ea41
Revises: 984965091a12
Create Date: 2022-09-04 17:10:03.257672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "462f2799ea41"
down_revision = "984965091a12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("post_date", sa.DateTime(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
