"""author_id fk and relationship on Comments model

Revision ID: 6bc8deda5332
Revises: f8f70049ef4d
Create Date: 2022-09-05 18:06:56.052532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bc8deda5332"
down_revision = "f8f70049ef4d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("author_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "comments", "users", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "author_id")
    # ### end Alembic commands ###
