"""__init__

Revision ID: 984965091a12
Revises: 
Create Date: 2022-08-31 19:43:15.496361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984965091a12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), unique=True, nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
